version: "3.6"
services:
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes: 
      - grafana-volume:/var/lib/grafana
    networks:
      - frontend
      - database
    ports:
      - 3000:3000
   
  influxdb:
    image: influxdb:1.8.10
    restart: unless-stopped
    volumes: 
      - influxdb-volume:/var/lib/influxdb
    networks:
      - database
    environment:
      - INFLUXDB_DB='p1data'
      - INFLUXDB_ADMIN_USER='admin'
      - INFLUXDB_ADMIN_PASSWORD='admin'
      - INFLUXDB_USER='user'
      - INFLUXDB_USER_PASSWORD='user'
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
       
  p1monitor:
    image: collinit/p1monitor
    depends_on:
      - influxdb 
    restart: unless-stopped 
    networks:
      - database
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
  grafana-volume:
  influxdb-volume:

networks:
  database:
  frontend:
  
