version: '3.9'
services:
  grafana:
    image: grafana-oss:latest
    restart: on-failure:5 
    volumes: 
      - grafana-volume: /var/lib/grafana
    networks:
      - frontend
      - database
    ports:
      - 3000:3000
      
  influxdb:
    image: influxdb:1.8.10
    restart: on-failure:5 
    volumes: 
      - influxdb-volume: /var/lib/influxdb
    networks:
      - database
    environment:
      - INFLUXDB_DB: p1data
      - INFLUXDB_ADMIN_USER: admin
      - INFLUXDB_ADMIN_PASSWORD: admin
      - INFLUXDB_USER: user
      - INFLUXDB_USER_PASSWORD: user
      
  p1monitor:
    image: collinmezach/p1monitor:latest
    restart: on-failure:5 
    networks:
      - database

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true

networks:
  database:
  frontend:
  
